### ISSUE TITLE
Set up a new function app for file scan

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#10]
### Description

Create new function app  `filescan` with access to the storage account that hosts the queue
 "functions_extension_version"  = "~4"
  "FUNCTIONS_WORKER_RUNTIME" = "dotnet-isolated"
  "dotnet_version" = "v7.0"

Function should have access to the storage account altinnXXXXstorage02 that contains the queue. 
Environement variables:

`QueueStorage` : can be duplicated from events
`"Platform:ApiStoragesEndpoint"`: https://platform.env.altinn.cloud/storage/api/v1/

### Tasks
- [x] Create a new function app resource in terraform
- [x] QA
- [x] Test

### Acceptance Criterias
- [x] Function should be able to pick up messages from the storage queue
- [x] Function should be able to send requests to the FileScan component
