### ISSUE TITLE
Update validation logic in app

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#11]
### Description

App should have configurable option to stop validation of there are data elements that have not yet been scanned or have failed the scan.

### Tasks
- [x] Decide on error message if an instance constains a data element that is pending and/or infected
- [x] Update logic in ValidationService to prevent non clean dataElements from passing the check
- [x] Unit tests
- [x] QA
- [x] Test

### Acceptance Criterias
- [x] An instance with one or more infected data elements should not pass validation
- [x] An instance  with one or more pending data elements should not pass validation
- [x] An instance  without pending or infected data elements should pass validation
- [x] An data element without the FileScanResult property should not be evaluated w.r.t. file scan
