### ISSUE TITLE
Set up regression test workflow

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#132]
### Description

Regression tests should be executed after every new deployment of the events component. 
The workflow should be hosted in this github repository and triggered as a part of the release pipeline in Azure DevOps. 

The tests already have the option of running an extended number of tests, and this option should be used for the regression tests. 

Storage and notifications already have this set up and can be used as inspiration. 

### Tasks

- [ ] Set up workflow for regression test AT
- [ ] Set up workflow for regression test TT
- [ ] Set up workflow for regression test Prod
- [ ] Set up trigger of workflow from AzDO release pipeline
- [ ] QA
- [ ] Manual testing

### Acceptance Criterias

Regression tests are executed after each new deployment

**Comment by acn-sbuad** [comment]
Full test set is being run for use case tests. We could consider closing the issue or triggering the use case test workflow after deploy. What do you think, @olebhansen  @SandGrainOne  ?

**Comment by SandGrainOne** [comment]
I think we should implement the same differentiation between use-case and regression as we have for storage and notifications. Even is the tests are the same for now.

**Comment by SandGrainOne** [comment]
We're more likely to rewrite parts of file-scan to accomodate the features added by "Defender for Storage".
