### ISSUE TITLE
Upgrade filescan-end-to-end app to version 4/8 of the template

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-file-scan#148]
### Description

We should consider updating the `filescan-end-to-end` to the latest versions of the app template. Apps can now be on dotnet 8 with version 8 of the backend and use the latest front-end changes by using version 4 of the frontend.

### Additional Information

We need to perform the same with the `storage-end-to-end` app as well. https://github.com/Altinn/altinn-storage/issues/366

### Tasks
- [x] Run the upgrade tool to get most changes automatically added
- [x] Build and test the changes
- [x] Update the docker file if not already done by the tool

### Acceptance Criteria

- [x] The new version of `filescan-end-to-end` works without functional changes

**Comment by acn-sbuad** [comment]
Use case tests running ok in all envs
