### ISSUE TITLE
Update flow for post dataElement

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#15]
### Description

Push data elements to queue

### Additional Information

Events already have a lot of the code needed to communicate with a storage queue.

### Tasks

- [ ] Define a IFileScanQueueClient for Storage
- [ ] Implement a FileScanQueueClient in Storage
- [ ] Use FileScanQueueClient during POST of new data blob if scan is required.
