### ISSUE TITLE
Create FileScan component

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#2]
### Description

We need a file scan component that can orchestrate the file scanning. 

### Consideration 

Should it run in a seperate namespace? Volumes aren't available there yet. 

### Tasks
- [x] Create an empty .net 7 application with a health check endpoint
- [x] Create helm charts for deployment: ensure service only runs in intended nodepool
- [x] Set up build/ release pipelines
- [x] Enable auto triggers 
- [x] Create analysis pipeline 
- [x] Set up container scan
~~- [ ] #27~~
- [x] QA
- [x] Test 

### Acceptance Criterias
- [x] Component is deployed to AT23
- [x] Deploy pipeline for YT, TT, PROD exists
- [x] Required actions in GitHub exists
~~- [ ] Should run in seperate namespace~~ limitations to volumes
- [x] Should run in correct node pool
