### ISSUE TITLE
Set up APIM for FileScan 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#21]
### Description

For the Azure Function to be able to communicate with the File Scan component it's API should be defined in APIM. 

### Considerations
No subscription key required. No check of header in APIM either, for now. 

### Tasks
- [x] Set up resource
- [x] Agree on policies 
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] Deployed to AT21
- [x] Deployed to AT22
- [x] Deployed to AT23
- [x] Deployed to AT24
- [x] Deployed to Yt01
- [x] Deployed to tt02
- [x] Deployed to prod
