### ISSUE TITLE
Upgrade File-scan to dotnet v9

### ISSUE THREAD

**Issue by hggutvik** [Altinn/altinn-file-scan#213]
### Description

We should upgrade the File-scan application to .net9. .net9 has standard time support until May 12, 2026, but we should take the time to upgrade and not wait for .net 10. 

### Additional Information

[.NET Core Support lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
[Container Patching](https://pedia.altinn.cloud/altinn-3/ops/patching/containers/#net-core)

### Tasks

- [x] Update base images in the dockerfile for .net9
- [x] Bump all projects; src and test, to .net9
- [x] Update any build pipelines to support .net9
- [x] Update any github workflows with .net9
- [ ] Check if we need to change anything in SonarCloud
- [ ] Make sure terraform changes is deployet BEFORE the application https://github.com/Altinn/altinn-platform/issues/1304

### Acceptance Criterias

- [ ] File-scan is built with .net9 tooling and runs on .net9
