### ISSUE TITLE
Complete implementation of unit tests for file scan component

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#36]
### Description

We merged the code for the file scan component before all unit tests we're implemented in the interest of time. These tests should be completed. 

### Tasks

- [ ] Implement unit tests
- [ ] Implement integration tests
- [ ] QA

### Acceptance Criterias

- [ ] Code coverage is within the requirements defined in SonarCloud
