### ISSUE TITLE
Implement use case tests

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#42]
### Description

We need a use case tests that verifies that all components of the file scan flow works as expected.

Test could be based on instantiation and completion of an app that has enabled filescan and validation alert based on pending scan

### Tasks
- [x] Define a basic end-to-end test that can run as a use case test 
- [x] Specify testing strategy using Github Workflows 
- [x] Set up use case tests pipeline
- [x] Set up notification to slack
- [x] QA
- [x] Verify set up for test and production

### Acceptance Criterias

- [x] Periodical workflow runs causing traffic for file scan
- [x] A failed test run should result in an alert to slack
- [x] Failed test run in AT goes to alerts-test
- [x] Failed test run in TT / prod goes to alerts-prod
