### ISSUE TITLE
Implement caching of certificate in function

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#52]
### Description

Currently a new access token is generated for each time a new function instance starts. This is affecting the performance of the filescan workflow. We should investigate how we can cache the access token inbetween function instances or look into alternative ways to authorize the request to the filescan component. 

Caching of certificate should be 1 hour
Also check that we cache the AccessToken. Should also be cached for 1 hour.

### Additional Information

This change has already been done in Events functions.

### Tasks

- [x] Add caching of the sertificate to the FileScan function
- [x] Review (QA)
- [x] Regression test
- [x] Verify kv access count has dropped 

### Acceptance Criterias

- [x] The certificate used in AccessToken signing is not downloaded for every function execution.
[Check kv access logs to confirm](https://portal.azure.com/#view/Microsoft_Azure_MonitoringMetrics/Metrics.ReactView/ResourceId/%2Fsubscriptions%2Fde41df22-8dd0-435b-98dd-6152cd371e92%2FresourceGroups%2Faltinnplatform-at22-rg%2Fproviders%2FMicrosoft.KeyVault%2Fvaults%2Faltinn-at22-kv/TimeContext~/%7B%22options%22%3A%7B%22grain%22%3A1%7D%2C%22relative%22%3A%7B%22duration%22%3A604800000%7D%7D/Chart~/%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2Fde41df22-8dd0-435b-98dd-6152cd371e92%2FresourceGroups%2Faltinnplatform-at22-rg%2Fproviders%2FMicrosoft.KeyVault%2Fvaults%2Faltinn-at22-kv%22%7D%2C%22name%22%3A%22ServiceApiHit%22%2C%22aggregationType%22%3A7%2C%22metricVisualization%22%3A%7B%22displayName%22%3A%22Total%20Service%20Api%20Hits%22%2C%22resourceDisplayName%22%3A%22altinn-at22-kv%22%7D%7D%5D%2C%22title%22%3A%22Total%20requests%22%2C%22titleKind%22%3A2%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A604800000%7D%2C%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22ActivityType%22%7D%2C%22visualization%22%3A%7B%22chartType%22%3A2%7D%7D/openInEditMode~/false)

**Comment by acn-sbuad** [comment]
![Image](https://github.com/Altinn/altinn-file-scan/assets/47737608/ed02832d-0de1-4c38-9eb8-333fc8f81720)

reduction in interactions with certificates in KV.
