### ISSUE TITLE
Update storage models

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#7]
### Description

Update storage interface to expose new properties for data element and dataTypes

### Tasks

- [x] Agree on new property names and placement of these
- [x] Update storage interface
- [x] QA
- [x] Push new puget package 
- [x] Ensure all central dependencies are updates

### Acceptance Criterias

- [x] New properties exists on the storage model
