### ISSUE TITLE
Set up new node pool for platform AKS

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#9]
### Description

Two new services are to run in the platform cluster, but they should be isolated in a separate node pool.

### Tasks
- [x] Investigate if configurations at node pool level can ensure that only file scan services run in the new node pool 
- [x] Update required terraform scrips
- [x] QA 
- [x] Test
- [x] Deploy to AT23
- [x] Deploy to YT01
- [x] Deploy to TT02
- [x] Deploy to PROD

### Acceptance Criterias

- [x] Ensure services running in node pool have access to app owner key vaults
- [x] Ensure services running in node pool have access to platform key vault

**Comment by tjololo** [comment]
Name of nodepool: filescan
Taint: workloads=filescan:NoSchedule
